config/routes.rb
Rails.application.routes.draw do
  resources :specialties
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :hospitals
  resources :home
  root :to  => "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/hospital_concern.rb
module HospitalConcern
  extend ActiveSupport::Concern
  include ActiveModel::Validations

  included do
    validates :hospital_name, :presence => true
    validates :mobile_number, :presence => true
    validates :address, :presence => true
    validates :landline_number, :presence => true
    validates :specialty_ids, :presence => true
    # has_many :taggings, as: :taggable
    # has_many :tags, through: :taggings
    STATE = [{ :name => 'AP', :id => '1' }, { :name => 'TG', :id => '2' }]
    DISTRICTS = [{ :name => 'Rangareddy', :id => '1' }, { :name => 'Hyderabad', :id => '2' },
                 { :name => 'Tirupathi', :id => '3' }, { :name => 'East Godhavari', :id => '4' },
                 { :name => 'Ongole', :id => '5' }]

  end

  # methods defined here are going to extend the class, not the instance of it
  module ClassMethods

  end
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  include HospitalConcern
  # serialize :specialty, Array
end

app/models/specialty.rb
class Specialty < ApplicationRecord
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  include ActionController::MimeResponds

  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
  layout :check_resource

  def check_resource

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper
  # decorates_assigned :hospital

  before_action :find_pin, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  def index
     smart_listing_create(:hospitals, Hospital.all, partial: "hospitals/hospital")
  end

  def show
  end

  def new
    @hospital = Hospital.new()
  end

  def edit
  end

  def create
    @hospital = Hospital.create(hospital_params)
  end

  def destroy
    @hospital.destroy
  end

  def update
    @hospital.update_attributes(hospital_params)
  end

  private

  def hospital_params
    params.require(:hospital).permit(:hospital_name, :mobile_number, :address, :landline_number, :number_of_beds, :specialty_ids => [])
  end

  def find_pin
    @hospital = Hospital.find(params[:id])
  end
end

app/controllers/specialties_controller.rb
class SpecialtiesController < ApplicationController
  before_action :set_specialty, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @specialties = Specialty.all
    respond_with(@specialties)
  end

  def show
    respond_with(@specialty)
  end

  def new
    @specialty = Specialty.new
    respond_with(@specialty)
  end

  def edit
  end

  def create
    @specialty = Specialty.new(specialty_params)
    @specialty.save
    respond_with(@specialty)
  end

  def update
    @specialty.update(specialty_params)
    respond_with(@specialty)
  end

  def destroy
    @specialty.destroy
    respond_with(@specialty)
  end

  private
    def set_specialty
      @specialty = Specialty.find(params[:id])
    end

    def specialty_params
      params.require(:specialty).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/specialties_helper.rb
module SpecialtiesHelper
end

app/views/hospitals/_form.html.haml
%td{colspan: 8}
  = simple_form_for object, remote: true, html: { multipart: true } do |f|
    - if @hospital.errors.any?
      #errors
        %h2
        = pluralize(@hospital.errors.count, 'error')
        prevented this Pin from saving
      -#%ul.errors
      -#  - @hospital.errors.full_messages.each do |msg|
      -#    %li= msg

    .form-group
      = f.input :hospital_name, input_html: {class: 'form-control'}, wrapper: :inline
    .form-group
      = f.input :mobile_number, input_html: {class: 'form-control'}, wrapper: :inline
    .form-group
      = f.input :address, input_html: {class: 'form-control'}, wrapper: :inline
    .form-group
      = f.input :landline_number, input_html: {class: 'form-control'}, wrapper: :inline
    .form-group
      = f.input :number_of_beds, input_html: {class: 'form-control'}, wrapper: :inline
    .form-group
      = f.collection_check_boxes :specialty_ids, Specialty.all, :id, :name, checked: (object.specialty_ids)? JSON.parse(object.specialty_ids) : nil do |cb|
        .form-check
          = cb.label class: 'form-check-label' do
            = cb.check_box class: 'form-check-input'
            = cb.text
    = f.submit 'Save', class: 'btn btn-primary btn-sm'
    %button.btn.btn-link.cancel Cancel

app/views/hospitals/_hos.html.haml
%td= object.hospital_name
%td= object.address
%td= object.mobile_number
%td= object.landline_number
%td= object.number_of_beds
%td= object.specialty_ids
%td.actions= smart_listing_item_actions [ {name:   :custom,
  url:  edit_hospital_path(object),   method: :put, remote: false},
 {name: :edit,    url: edit_hospital_path(object)},
 {name: :destroy, url: hospital_path(object), confirmation: "Are you sure you want to delete this?"}]

app/views/hospitals/_hospital.html.haml
%table.table.table-striped.table-hover
  %thead
    %tr
      %th= smart_listing.sortable "Hospital Name", :hospital_name
      %th Address
      %th Mobile Number
      %th Landline Number
      %th Bed Capacity
  %tbody
    - smart_listing.collection.each do |hospital|
      %tr.editable{data: {id: hospital.id}}
        = smart_listing.render object: hospital, partial: "hospitals/hos", locals: {object: hospital}

    = smart_listing.item_new colspan: 8, link: new_hospital_path


= smart_listing.paginate

app/views/hospitals/create.js.erb
<%= smart_listing_item :hospitals, :create, @hospital,
                       @hospital.valid? ? "hospitals/hos" : "hospitals/form" %>

app/views/hospitals/destroy.js.erb
<%= smart_listing_item :hospitals, :destroy, @hospital %>

app/views/hospitals/edit.js.erb
<%= smart_listing_item :hospitals, :edit, @hospital, 'hospitals/form' %>

app/views/hospitals/index.html.haml
-#%h1 Hospitals#index
-#- @hospitals.each do |hospital|
-#  .box.panel.panel-default
-#    .panle-body
-#      = hospital.mobile_number
-#      = Hospital::STATE.collect {|p| p[:name] if hospital.state == p[:id].to_i }[0]
-#      = Hospital::DISTRICTS.collect {|p| p[:name] if hospital.district == p[:id].to_i }[0]
-#      = Hospital::DISTRICTS.collect {|p| p[:name] if hospital.mandal == p[:id].to_i }[0]
-#
-#= link_to "New Hospital", new_hospital_path, class: "btn btn-default"
= smart_listing_render(:hospitals)
-#= link_to "New Hospital", new_hospital_path, class: "btn btn-default btn-sm"

app/views/hospitals/index.js.erb
<%= smart_listing_update(:hospitals) %>

app/views/hospitals/new.js.erb
<%= smart_listing_item :hospitals, :new, @hospital, "hospitals/form" %>

app/views/hospitals/show.html.haml
%h1 Hospitals#show
.row
  .col-md-8.col-md-offset-2
    .panel.panel-default
      .panel-body
        %p.mobile_number= @hospital.mobile_number
        %p.mobile_number= @hospital.state
        %p.mobile_number= @hospital.district
        %p.mobile_number= @hospital.mandal
        %p.mobile_number= @hospital.village
      .panel-footer
        .row
          .col-md-6
            .btn-group.pull-right
              = link_to "Edit", edit_hospital_path, class: "btn btn-default"
              = link_to "Delete", hospital_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default"

app/views/hospitals/update.js.erb
<%= smart_listing_item :hospitals, :update, @hospital,
                       @hospital.valid? ? "hospitals/hos" : "hospitals/form" %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HandyHealth
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    -#%nav.navbar.navbar-default
    -#  .container-fluid
    -#    .navbar-brand= link_to "HandyHealth", root_path
    -#    - if true
    -#      %ul.nav.navbar-nav.navbar-right
    -#        %li= link_to "Hospital Info", hospitals_path
    -#        %li= link_to "Lab Info", root_path
    -#        %li
    -#          -#%input{:checked => "checked", "data-toggle" => "toggle", "data-on": "English",  "data-off":"Telugu", :type => "checkbox"}
    -#    - else
    -#      %ul.nav.navbar-nav.navbar-right
    -#        %li= link_to "Sign Up", root_path
    -#        %li= link_to "Sign In", root_path
      %nav.navbar.navbar-default
    %nav.navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#{root_path}"} HandyHealth
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li= link_to "Hospital Info", hospitals_path
            %li
              %a{:href => "#"} Link
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                Dropdown
                %span.caret
              %ul.dropdown-menu{:role => "menu"}
                %li
                  %a{:href => "#"} Action
                %li
                  %a{:href => "#"} Another action
                %li
                  %a{:href => "#"} Something else here
                %li.divider
                %li
                  %a{:href => "#"} Separated link
                %li.divider
                %li
                  %a{:href => "#"} One more separated link
          %form.navbar-form.navbar-left{:role => "search"}
            .form-group
              %input.form-control{:placeholder => "Search", :type => "text"}/
            %button.btn.btn-default{:type => "submit"} Submit
          %ul.nav.navbar-nav.navbar-right
            %li
              %a{:href => "#"} Link


    -#.container
    -#  %ul.bxslider
    -#    %li
    -#      %img{:src => '/assets/images.jpg', width: "40%" }
    -#    %li
    -#      %img{:src => '/assets/images1.jpg', width: "40%"}
    -#    %li
    -#      %img{:src => '/assets/images2.jpg', width: "40%"}
    -#    %li
    -#      %img{:src => '/assets/images3.jpg', width: "40%"}
    .container
      - flash.each do |name, msg|
        = content_tag :div, msg, class: "alert alert-info"
      = yield

app/views/smart_listing/_action_custom.html.erb
<%# 
  Custom action.

  Available local variables:
    url
    icon
    html_options:       custom html options
-%>

<%= link_to_if(action_if, content_tag(:span, '', :class => icon, :title => title), url, html_options) %>

app/views/smart_listing/_action_delete.html.erb
<%# 
  Delete action.

  Available local variables:
    action_if:          false if action is disabled
    url:                destroy url
    icon:               icon css classes
    confirmation:       confrimation text
    title
-%>

<%= link_to_if(action_if, content_tag(:i, "", :class => icon), url, :remote => true, :class => "destroy", :method => :delete, :title => title || t("smart_listing.actions.destroy"), :data => {:confirmation => confirmation || t("smart_listing.msgs.destroy_confirmation")} ) %>

app/views/smart_listing/_action_edit.html.erb
<%# 
  Edit action.

  Available local variables:
    action_if:          false if action is disabled
    url:                edit url
    icon:               icon css classes
    title
-%>

<%= link_to_if(action_if, content_tag(:i, '', :class => icon), url, :remote => true, :class => "edit", :title => title || t("smart_listing.actions.edit") ) %>

app/views/smart_listing/_action_show.html.erb
<%# 
  Show action.

  Available local variables:
    action_if:          false if action is disabled
    url:                show url
    icon:               icon clss classes
    title
-%>

<%= link_to_if(action_if, content_tag(:i, '', :class => icon), url, :class => "show", :title => title || t("smart_listing.actions.show") ) %>

app/views/smart_listing/_item_new.html.erb
<%# 
  New list item element (contains new item placeholder and add button).

  Available local variables:
    placeholder_classes:      classes for the main container
    new_item_action_classes:  new item action classes
    colspan              
    no_items_classes:         no items container classes
    no_items_text:            no items text displayed inside container
    new_item_button_url:      argument to link_to (new item button)
    new_item_button_classes
    new_item_button_text
    new_item_autoshow         automatically show new item placeholder
    new_item_content          new item placeholder content (usually some form)
-%>

<%= content_tag(:tr, '', :class => placeholder_classes + %w{info}, :data => {smart_listing_config.data_attributes(:autoshow) => new_item_autoshow}) do %>
  <%= new_item_content %>
<% end %>
<%= content_tag(:tr, :class => new_item_action_classes + %w{info}) do %>
  <%= content_tag(:td, :colspan => colspan) do %>
    <%= content_tag(:p, :class => no_items_classes + %w{pull-left}) do %>
      <%= no_items_text %>
    <% end %>
    <%= link_to(new_item_button_url, :remote => true, :class => new_item_button_classes + %w{btn pull-right}) do %>
      <%= content_tag(:i, '', :class => smart_listing_config.classes(:icon_new)) %>
      <%= new_item_button_text %>
    <% end %>
  <% end %>
<% end %>

app/views/smart_listing/_pagination_per_page_link.html.erb
<%# 
  Pagination single per-page link.

  Available local variables:
    page:           page number
    url:            page url (if page is not selected)
    smart_listing:  current SmartListing instance
    builder:        current builder instance
-%>

<% name = page == 0 ? t('views.pagination.unlimited') : page %>
<%= url ? link_to(name, url, :remote => smart_listing.remote?) : content_tag(:span, name) %>

app/views/smart_listing/_pagination_per_page_links.html.erb
<%# 
  Pagination per-page links.

  Available local variables:
    container_classes:  classes for the main container
    per_page_sizes:     array of available per-page sizes
    smart_listing:      current SmartListing instance
    builder:            current builder instance
-%>

<%= content_tag(:div, :class => container_classes ) do %>
  <% if smart_listing.options[:paginate] && (smart_listing.count > smart_listing.page_sizes.first) %>
    <%= t('views.pagination.per_page') %>
    <% per_page_sizes.each do |p| %><%= builder.pagination_per_page_link p %><% break if p >= smart_listing.count %><% end %>
    |
  <% end %>
  <%= t('views.pagination.total') %>
  <%= content_tag(:span, smart_listing.count, :class => "count") %>
<% end %>

app/views/smart_listing/_sortable.html.erb
<%# 
  Sortable attribute listing header.

  Available local variables:
    container_classes:  classes for the main container
    url:                sortable link url
    attribute:          current attribute name
    title:              current attribute title
    order:              defines column sort order
    smart_listing:      current SmartListing instance
    builder:            current builder instance
-%>

<%= link_to url, :class => container_classes, :data => {:attr => attribute}, :remote => true do %>
  <%= title %>
  <% if order %>
    <span class="<%= order == "asc" ? smart_listing_config.classes(:icon_sort_up) : smart_listing_config.classes(:icon_sort_down) %>"></span>
  <% else %>
    <span class="<%= smart_listing_config.classes(:icon_sort_none) %>"></span>
  <% end %>
<% end %>

app/views/specialties/_form.html.haml
= simple_form_for(@specialty) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/specialties/edit.html.haml
%h1 Editing specialty

= render 'form'

= link_to 'Show', @specialty
\|
= link_to 'Back', specialties_path

app/views/specialties/index.html.haml
%h1 Listing specialties

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @specialties.each do |specialty|
      %tr
        %td= specialty.name
        %td= link_to 'Show', specialty
        %td= link_to 'Edit', edit_specialty_path(specialty)
        %td= link_to 'Destroy', specialty, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Specialty', new_specialty_path

app/views/specialties/new.html.haml
%h1 New specialty

= render 'form'

= link_to 'Back', specialties_path

app/views/specialties/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @specialty.name

= link_to 'Edit', edit_specialty_path(@specialty)
\|
= link_to 'Back', specialties_path